/* Extracts the centreline of the logo's gold swoosh from the traced gold mask,
   so the site's step line is the logo's own curve, not an approximation.
   Output: src/swoosh-line.js, points normalised to the swoosh bbox (0..1),
   plus the stroke width profile (thick middle, tapered ends). */
import fs from 'node:fs';
const W = 4647, H = 3045;
const buf = fs.readFileSync('tools/tmp/gold.pgm');
const data = buf.subarray(buf.length - W * H);
const ink = (x, y) => data[y * W + x] < 128;
const X0 = 1118, X1 = 3297, Y0 = 1280, Y1 = 1815;
const pts = [];
for (let x = X0; x <= X1; x += 6) {
  // runs in this column; the swoosh is the lowest run (the foot sits on top of it)
  const runs = []; let start = -1;
  for (let y = Y0; y <= Y1; y++) {
    if (ink(x, y) && start < 0) start = y;
    if (!ink(x, y) && start >= 0) { runs.push([start, y - 1]); start = -1; }
  }
  if (start >= 0) runs.push([start, Y1]);
  if (!runs.length) continue;
  const [a, b] = runs[runs.length - 1];
  pts.push([x, (a + b) / 2, b - a + 1]);
}
// simplify: keep every Nth point plus ends, then normalise
const step = Math.ceil(pts.length / 24);
const keep = pts.filter((_, i) => i % step === 0 || i === pts.length - 1);
const bx0 = 1115.6, bx1 = 3299.3, by0 = 1292.4, by1 = 1808.4;
const norm = keep.map(([x, y, t]) => [+((x - bx0) / (bx1 - bx0)).toFixed(4), +((y - by0) / (by1 - by0)).toFixed(4), +(t / (bx1 - bx0)).toFixed(4)]);
fs.writeFileSync('src/swoosh-line.js', '// generated by tools/swoosh-line.mjs from the traced logo, do not edit\n// [x, y, thickness] normalised to the swoosh bounding box\nexport default ' + JSON.stringify(norm) + ';\n');
console.log(norm.length, 'points; thickness range', Math.min(...norm.map(p => p[2])), '-', Math.max(...norm.map(p => p[2])));
console.log(norm.map(p => p.slice(0, 2).join(',')).join('  '));
